# Generated by Django 5.0.7 on 2024-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('post_title', models.CharField(max_length=255)),
                ('post_text', models.TextField()),
            ],
        ),
    ]
